apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mike
  annotations:
   backstage.io/kubernetes-id: pizza
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
