apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: duke
  backstage.io/kubernetes-id: noob
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
