apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nike
  annotations:
   backstage.io/kubernetes-id: hawk
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
